export const STAGE_MODELS = {
  "stage1-splitting": { provider: "openai", model: "gpt-4o" },
  "stage2-matching": { provider: "openai", model: "gpt-4o" },
  "stage5-commentary": { provider: "openai", model: "gpt-4o" },
  "editorial-review": { provider: "openai", model: "gpt-4o" },
  "editorial-style-review": { provider: "openai", model: "gpt-4o" },
  "compliance-review": { provider: "openai", model: "gpt-4o" },
  "style-review": { provider: "openai", model: "gpt-4o" },
  "detect-output-type": { provider: "openai", model: "gpt-4o-mini" },

  "claim-extraction": { provider: "openai", model: "gpt-4o-mini" },
  "claim-verifier": { provider: "openai", model: "gpt-4o-mini" },
  "writing-generate": { provider: "openai", model: "gpt-5.1" },
  "writing-rewrite": { provider: "openai", model: "gpt-5.1" },
  adapt: { provider: "openai", model: "gpt-5.1" },
  "ask-query": { provider: "openai", model: "gpt-5.1" },
  "query-sources": { provider: "openai", model: "gpt-5.1" },
  "summarize-source": { provider: "openai", model: "gpt-4o-mini" },
  "summarize-source-usage": { provider: "openai", model: "gpt-4o-mini" },
  "summarize-rewrite-label": { provider: "openai", model: "gpt-4o-mini" },
  "synthesize-review": { provider: "openai", model: "gpt-4o" },
  "constructive-feedback": { provider: "openai", model: "gpt-4o" },
  "output-scoring": { provider: "openai", model: "gpt-4o-mini" },
  "editorial-duplication-judge": { provider: "openai", model: "gpt-4o-mini" },
};
